export const dtcCodes = [
  { code: "P0100", description: "Mass or Volume Air Flow Circuit Malfunction" },
  { code: "P0101", description: "Mass or Volume Air Flow Circuit Range/Performance Problem" },
  { code: "P0102", description: "Mass or Volume Air Flow Circuit Low Input" },
  { code: "P0103", description: "Mass or Volume Air Flow Circuit High Input" },
  { code: "P0104", description: "Mass or Volume Air Flow Circuit Intermittent" },
  { code: "P0105", description: "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction" },
  { code: "P0106", description: "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem" },
  { code: "P0107", description: "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input" },
  { code: "P0108", description: "Manifold Absolute Pressure/Barometric Pressure Circuit High Input" },
  { code: "P0109", description: "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent" },
  // New codes added below
  { code: "P0533", description: "A/C Refrigerant Pressure Sensor Circuit Low Input" },
  { code: "P0534", description: "A/C Refrigerant Pressure Sensor Circuit High Input" },
  { code: "P0550", description: "Air Conditioner Refrigerant Charge Loss" },
  { code: "P0551", description: "Power Steering Pressure Sensor Circuit Malfunction" },
  { code: "P0552", description: "Power Steering Pressure Sensor Circuit Range/Performance" },
  { code: "P0553", description: "Power Steering Pressure Sensor Circuit Low Input" },
  { code: "P0554", description: "Power Steering Pressure Sensor Circuit High Input" },
  { code: "P0560", description: "Power Steering Pressure Sensor Circuit Intermittent" },
  { code: "P0561", description: "System Voltage Malfunction" },
  { code: "P0562", description: "System Voltage Unstable" },
  { code: "P0563", description: "A/C pressure sensor low voltage(Chrysler)" },
  { code: "P0565", description: "System Voltage High" },
  { code: "P0566", description: "Cruise Control On Signal Malfunction" },
  { code: "P0567", description: "Cruise Control Off Signal Malfunction" },
  { code: "P0568", description: "Cruise Control Resume Signal Malfunction" },
  { code: "P0569", description: "Cruise Control Set Signal Malfunction" },
  { code: "P0570", description: "Cruise Control Coast Signal Malfunction" },
  { code: "P0571", description: "Cruise Control Accel Signal Malfunction" },
  { code: "P0572", description: "Cruise Control/Brake Switch A Circuit Malfunction" },
  { code: "P0573", description: "Cruise Control/Brake Switch A Circuit Low" },
  { code: "P0574", description: "Cruise Control/Brake Switch A Circuit High" },
  { code: "P0575", description: "Cruise Control Related Malfunction" },
  { code: "P0576", description: "Cruise Control Related Malfunction" },
  { code: "P0578", description: "Cruise Control Related Malfunction" },
  { code: "P0579", description: "Cruise Control Related Malfunction" },
  { code: "P0580", description: "Cruise Control Related Malfunction" },
  { code: "P0600", description: "Cruise Control Related Malfunction" },
  { code: "P0601", description: "Serial Communication Link Malfunction" },
  { code: "P0602", description: "Control Module Read Only Memory(ROM)" },
  { code: "P0603", description: "Control Module Programming Error" },
  { code: "P0604", description: "Internal Control Module Keep Alive Memory (KAM) Error" },
  { code: "P0605", description: "Internal Control Module Random Access Memory (RAM) Error" },
  { code: "P0606", description: "Internal Control Module Read Only Memory (ROM) Error" },
  { code: "P0608", description: "PCM Processor Fault" },
  { code: "P0609", description: "Control Module VSS Output \"A\" Malfunction" },
  { code: "P0620", description: "Control Module VSS Output \"B\" Malfunction" },
  { code: "P0621", description: "Generator Control Circuit Malfunction" },
  { code: "P0622", description: "Generator Lamp \"L\" Control Circuit Malfunction" },
  { code: "P0650", description: "Generator Field \"F\" Control Circuit Malfunction" },
  { code: "P0654", description: "Malfunction Indicator Lamp (MIL) Control Circuit Malfunction" },
  { code: "P0655", description: "Engine RPM Output Circuit Malfunction" },
  { code: "P0656", description: "Engine Hot Lamp Output Control Circuit Malfucntion" },
  { code: "P0700", description: "Fuel Level Output Circuit Malfunction" },
  { code: "P0701", description: "Transmission Control System Malfunction" },
  { code: "P0702", description: "Transmission Control System Range/Performance" },
  { code: "P0703", description: "Transmission Control System Electrical" },
  { code: "P0704", description: "Torque Converter/Brake Switch B Circuit Malfunction" },
  { code: "P0705", description: "Clutch Switch Input Circuit Malfunction" },
  { code: "P0706", description: "Transmission Range Sensor Circuit malfunction (PRNDL Input)" },
  { code: "P0707", description: "Transmission Range Sensor Circuit Range/Performance" },
  { code: "P0708", description: "Transmission Range Sensor Circuit Low Input" },
  { code: "P0709", description: "Transmission Range Sensor Circuit High Input" },
  { code: "P0710", description: "Transmission Range Sensor Circuit Intermittent" },
  { code: "P0711", description: "Transmission Fluid Temperature Sensor Circuit Malfunction" },
  { code: "P0712", description: "Transmission Fluid Temperature Sensor Circuit Range/Performance" },
  { code: "P0713", description: "Transmission Fluid Temperature Sensor Circuit Low Input" },
  { code: "P0714", description: "Transmission Fluid Temperature Sensor Circuit High Input" },
  { code: "P0715", description: "Transmission Fluid Temperature Sensor Circuit Intermittent" },
  { code: "P0716", description: "Input/Turbine Speed Sensor Circuit Malfunction" },
  { code: "P0717", description: "Input/Turbine Speed Sensor Circuit Range/Performance" },
  { code: "P0718", description: "Input/Turbine Speed Sensor Circuit No Signal" },
  { code: "P0719", description: "Input/Turbine Speed Sensor Circuit Intermittent" },
  { code: "P0720", description: "Torque Converter/Brake Switch B Circuit Low" },
  { code: "P0721", description: "Output Speed Sensor Circuit Malfunction" },
  { code: "P0722", description: "Output Speed Sensor Range/Performance" },
  { code: "P0723", description: "Output Speed Sensor No Signal" },
  { code: "P0724", description: "Output Speed Sensor Intermittent" },
  { code: "P0725", description: "Torque Converter/Brake Switch B Circuit High" },
  { code: "P0726", description: "Engine Speed input Circuit Malfunction" },
  { code: "P0727", description: "Engine Speed Input Circuit Range/Performance" },
  { code: "P0728", description: "Engine Speed Input Circuit No Signal" },
  { code: "P0730", description: "Engine Speed Input Circuit Intermittent" },
  { code: "P0731", description: "Incorrect Gear Ratio" },
  { code: "P0732", description: "Gear 1 Incorrect ratio" },
  { code: "P0733", description: "Gear 2 Incorrect ratio" },
  { code: "P0734", description: "Gear 3 Incorrect ratio" },
  { code: "P0735", description: "Gear 4 Incorrect ratio" },
  { code: "P0736", description: "Gear 5 Incorrect ratio" },
  { code: "P0740", description: "Reverse incorrect gear ratio" },
  { code: "P0741", description: "Torque Converter Clutch Circuit Malfuction" },
  { code: "P0742", description: "Torque Converter Clutch Circuit Performance or Stuck Off" },
  { code: "P0743", description: "Torque Converter Clutch Circuit Stuck On" },
  { code: "P0744", description: "Torque Converter Clutch Circuit Electrical" },
  { code: "P0745", description: "Torque Converter Clutch Circuit Intermittent" },
  { code: "P0746", description: "Pressure Control Solenoid Malfunction" },
  { code: "P0747", description: "Pressure Control Solenoid Performance or Stuck Off" },
  { code: "P0748", description: "Pressure Control Solenoid Stuck On" },
  { code: "P0749", description: "Pressure Control Solenoid Electrical" },
  { code: "P0750", description: "Pressure Control Solenoid Intermittent" },
  { code: "P0751", description: "Shift Solenoid A Malfunction" },
  { code: "P0752", description: "Shift Solenoid A Performance or Stuck Off" },
  { code: "P0753", description: "1-2 Shift Solenoid Valve Performance" },
  { code: "P0754", description: "Shift Solenoid A Stuck On" },
  { code: "P0755", description: "Shift Solenoid A Electrical" },
  { code: "P0756", description: "1-2 Shift Solenoid Circuit Electrical" },
  { code: "P0757", description: "Shift Solenoid A Intermittent" },
  { code: "P0758", description: "Shift Solenoid B Malfunction" },
  { code: "P0759", description: "Shift Solenoid B Performance or Stuck Off" },
  { code: "P0760", description: "2-3 Shift Solenoid Valve Performance" },
  { code: "P0761", description: "Shift Solenoid B Stuck On" },
  { code: "P0762", description: "Shift Solenoid B Electrical/ 2-3 Shift Solenoid Circuit Electrical" },
  { code: "P0763", description: "Shift Solenoid B Intermittent" },
  { code: "P0764", description: "Shift Solenoid C Malfunction" },
  { code: "P0765", description: "Shift Solenoid C Performance or Stuck Off" },
  { code: "P0766", description: "Shift Solenoid C Stuck On" },
  { code: "P0767", description: "Shift Solenoid C Electrical" },
  { code: "P0768", description: "Shift Solenoid C Intermittent" },
  { code: "P0769", description: "Shift Solenoid D Malfunction" },
  { code: "P0770", description: "Shift Solenoid D Performance or Stuck Off" },
  { code: "P0771", description: "Shift Solenoid D Stuck On" },
  { code: "P0772", description: "Shift Solenoid D Electrical" },
  { code: "P0773", description: "Shift Solenoid D Intermittent" },
  { code: "P0774", description: "Shift Solenoid E Malfunction" },
  { code: "P0775", description: "Shift Solenoid E Performance or Stuck Off" },
  { code: "P0776", description: "Shift Solenoid E Stuck On" },
  { code: "P0777", description: "Shift Solenoid E Electrical" },
  { code: "P0778", description: "Shift Solenoid E Intermittent" },
  { code: "P0779", description: "Pressure Control Solenoid B Malfunction" },
  { code: "P0780", description: "Pressure Control Solenoid B Performance" },
  { code: "P0781", description: "Pressure Control Solenoid B Stuck On" },
  { code: "P0782", description: "Pressure Control Solenoid B Electrical" },
  { code: "P0783", description: "Pressure Control Solenoid B Intermittent" },
  { code: "P0784", description: "Shift Malfunction" },
  { code: "P0785", description: "1-2 Shift Malfunction" },
  { code: "P0786", description: "2-3 Shift Malfunction" },
  { code: "P0787", description: "3-4 Shift Malfunction" },
  { code: "P0788", description: "4-5 Shift Malfunction" },
  { code: "P0789", description: "Shift/Timing Solenoid Malfunction/ 3-2 Shift Solenoid Circuit Electrical" },
  { code: "P0790", description: "Shift/Timing Solenoid Range/Performance" },
  { code: "P0801", description: "Shift/Timing Solenoid Low" },
  { code: "P0803", description: "Shift/Timing Solenoid High" },
  { code: "P0804", description: "Shift/Timing Solenoid Intermittent" },
  { code: "P1100", description: "Normal/Performance Switch Circuit Malfunction" },
  { code: "P1101", description: "Reverse Inhibit Control Circuit Malfunction" },
  { code: "P1102", description: "1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction" },
  { code: "P1103", description: "1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction" },
  { code: "P1104", description: "MAF Sensor Intermittent/ Check of all OBDII Systems Not Complete" },
  { code: "P1105", description: "MAF Sensor Out Of Self Test Range." },
  { code: "P1106", description: "KOER Not Able To Complete  KOER Aborted" },
  { code: "P1107", description: "MAF Sensor In Range But Lower Than Expected" },
  { code: "P1108", description: "MAF Sensor In Range But Higher Than Expected" },
  { code: "P1109", description: "MAF Ground Malfunction" },
  { code: "P1110", description: "Dual Alternator Upper Fault" },
  { code: "P1111", description: "Dual Alternator Lower Fault/ Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent High Voltage" },
  { code: "P1112", description: "Dual Alternator Lower Circuit Malfunction/ Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent Low Voltage" },
  { code: "P1113", description: "Dual Alternator Battery Lamp Circuit Malfunction" },
  { code: "P1114", description: "IAT - B Sensor Intermittent" },
  { code: "P1115", description: "IAT Sensor (D/C) Open/Short" },
  { code: "P1116", description: "Intake Air Temperature (IAT) Sensor Circuit Intermittent High Voltage" },
  { code: "P1117", description: "Intake Air Temperature (IAT) Sensor Circuit Intermittent Low Voltage" },
  { code: "P1118", description: "IAT Sensor Open/Short" },
  { code: "P1119", description: "Engine Coolant Temperature (ECT) Sensor Circuit Intermittent Low Voltage/IAT - B Circuit Low Input" },
  { code: "P1120", description: "Engine Coolant Temperature (ECT) Sensor Circuit Intermittent High Voltage/IAT - B Circuit High Input" },
  { code: "P1121", description: "Engine Coolant sensor out of range/ECT Sensor Out Of Self Test Range" },
  { code: "P1122", description: "Engine Coolant Sensor intermittent/ECT Sensor Intermittent" },
  { code: "P1123", description: "Manifold Absolute Temperature Circuit Low Input" },
  { code: "P1124", description: "Manifold Absolute Temperature Circuit High Input" },
  { code: "P1125", description: "Throttle position sensor out of range" },
  { code: "P1126", description: "Throttle Position (TP) Sensor Circuit Intermittent High Voltage" },
  { code: "P1127", description: "Throttle Position (TP) Sensor Circuit Intermittent Low Voltage" },
  { code: "P1128", description: "Throttle Position Sensor In Range But Higher Than Expected" },
  { code: "P1129", description: "Throttle Position Sensor Out Of Self Test Range" },
  { code: "P1130", description: "Throttle position sensor intermittent" },
  { code: "P1131", description: "Throttle Position (Narrow Range) Sensor Circuit Malfunction" },
  { code: "P1132", description: "Exhaust Not Warm" },
  { code: "P1133", description: "Upstream Heated O2 Sensors Swapped" },
  { code: "P1134", description: "Downstream Heated O2 Sensors Swapped" },
  { code: "P1135", description: "Lack Of HO2S Switch - Adaptive Fuel At Limit" },
  { code: "P1136", description: "Lack Of HO2S Switch - Sensor Indicates Lean" },
  { code: "P1137", description: "Lack Of HO2S Switch - Sensor Indicates Rich" },
  { code: "P1138", description: "HO2S Insufficient Switching Sensor 1" },
  { code: "P1139", description: "HO2S Transition Time Ratio Sensor 1" },
  { code: "P1140", description: "Pedal Position Sensor A Circuit Intermittent" },
  { code: "P1141", description: "Fan Control Circuit Malfunction" },
  { code: "P1142", description: "Lack Of HO2S Switch - Sensor Indicates Lean" },
  { code: "P1143", description: "Lack Of HO2S12 Switch - Sensor Indicates Rich" },
  { code: "P1144", description: "Water In Fuel Indicator Circuit Malfunction" },
  { code: "P1150", description: "Water In Fuel Condition" },
  { code: "P1151", description: "Fuel Restriction Indicator Circuit Malfunction" },
  { code: "P1152", description: "Fuel Restriction Condition" },
  { code: "P1153", description: "Air Assist Control Valve Range/Performance" },
  { code: "P1154", description: "Air Assist Control Valve Circuit Malfunction" },
  { code: "P1155", description: "Lack Of HO2S21 Switch - Adaptive Fuel At Limit" },
  { code: "P1156", description: "Lack Of HO2S21 Switch - Sensor Indicates Lean" },
  { code: "P1157", description: "Lack Of HO2S21 Switch - Sensor Indicates Rich" },
  { code: "P1158", description: "Bank 2 Fuel Control Shifted Lean" },
  { code: "P1159", description: "Bank 2 Fuel Control Shifted Rich" },
  { code: "P1167", description: "Alternative Fuel Controller" },
  { code: "P1168", description: "Fuel Select Switch Malfunction" },
  { code: "P1169", description: "Lack Of HO2S22 Switch - Sensor Indicates Lean" },
  { code: "P1170", description: "Lack Of HO2S22 Switch - Sensor Indicates Rich" },
  { code: "P1171", description: "Fuel Stepper Motor Malfunction" },
  { code: "P1172", description: "Invalid Test" },
  { code: "P1173", description: "Fuel Rail Sensor In-Range Low Failure" },
  { code: "P1174", description: "Fuel Rail Sensor In-Range High Failure" },
  { code: "P1175", description: "ESO - Engine Shut Off Solenoid Fault" },
  { code: "P1176", description: "Rotor Sensor Fault" },
  { code: "P1177", description: "Rotor Control Fault" },
  { code: "P1178", description: "Rotor Calibration Fault" },
  { code: "P1180", description: "Cam Sensor Fault" },
  { code: "P1181", description: "Cam Control Fault" },
  { code: "P1182", description: "Cam Calibration Fault" }
];