export const dtcCodes = [
  { code: "P0101", description: "Mass Air Flow (MAF) Circuit Range/Performance" },
  { code: "P0102", description: "Mass Air Flow (MAF) Circuit Low Input" },
  { code: "P0103", description: "Mass Air Flow (MAF) Circuit High Input" },
  { code: "P0110", description: "Intake Air Temperature (IAT) Sensor Circuit Malfunction" },
  { code: "P0113", description: "Intake Air Temperature (IAT) Sensor Circuit High Input" },
  { code: "P0117", description: "Engine Coolant Temperature (ECT) Sensor Circuit Low Input" },
  { code: "P0128", description: "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)" },
  { code: "P0131", description: "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)" },
  { code: "P0133", description: "O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)" },
  { code: "P0135", description: "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)" },
  { code: "P0151", description: "O2 Sensor Circuit Low Voltage (Bank 2, Sensor 1)" },
  { code: "P0171", description: "System Too Lean (Bank 1)" },
  { code: "P0172", description: "System Too Rich (Bank 1)" },
  { code: "P0174", description: "System Too Lean (Bank 2)" },
  { code: "P0300", description: "Random/Multiple Cylinder Misfire Detected" },
  { code: "P0301", description: "Cylinder 1 Misfire Detected" },
  { code: "P0302", description: "Cylinder 2 Misfire Detected" },
  { code: "P0303", description: "Cylinder 3 Misfire Detected" },
  { code: "P0304", description: "Cylinder 4 Misfire Detected" },
  { code: "P0401", description: "Exhaust Gas Recirculation (EGR) Flow Insufficient Detected" },
  { code: "P0402", description: "Exhaust Gas Recirculation (EGR) Flow Excessive Detected" },
  { code: "P0403", description: "Exhaust Gas Recirculation Control Circuit Malfunction" },
  { code: "P0410", description: "Secondary Air Injection System Malfunction" },
  { code: "P0411", description: "Secondary Air Injection System Incorrect Flow Detected" },
  { code: "P0412", description: "Secondary Air Injection System Switching Valve A Circuit Malfunction" },
  { code: "P0420", description: "Catalyst System Efficiency Below Threshold (Bank 1)" },
  { code: "P0422", description: "Main Catalyst Efficiency Below Threshold (Bank 1)" },
  { code: "P0430", description: "Catalyst System Efficiency Below Threshold (Bank 2)" },
  { code: "P0440", description: "Evaporative Emission Control System Malfunction" },
  { code: "P0441", description: "Evaporative Emission Control System Incorrect Purge Flow" },
  { code: "P0442", description: "Evaporative Emission Control System Leak Detected (small leak)" },
  { code: "P0446", description: "Evaporative Emission Control System Vent Control Circuit" },
  { code: "P0450", description: "Evaporative Emission Control System Pressure Sensor Malfunction" },
  { code: "P0452", description: "Evaporative Emission Control System Pressure Sensor Low Input" },
  { code: "P0453", description: "Evaporative Emission Control System Pressure Sensor High Input" },
  { code: "P0455", description: "Evaporative Emission Control System Leak Detected (large leak)" },
  { code: "P0460", description: "Fuel Level Sensor Circuit Malfunction" },
  { code: "P0500", description: "Vehicle Speed Sensor Malfunction" },
  { code: "P0700", description: "Transmission Control System (MIL Request)" },
  { code: "P0730", description: "Incorrect Gear Ratio" },
  { code: "P0740", description: "Torque Converter Clutch Circuit Malfunction" },
  { code: "P0750", description: "Shift Solenoid A Malfunction" },
  { code: "P0755", description: "Shift Solenoid B Malfunction" },
  { code: "P0760", description: "Shift Solenoid C Malfunction" },
  { code: "P0770", description: "Shift Solenoid E Malfunction" },
];